apiVersion: v1
kind: PersisteVolumeClaim
metadata:
  name: sample-pvc
spec:
  selector:
    matchLabels:
      type: "nfs"
    matchExpressions:
      - {key: environment, operator: In, values: [stg]}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
